name 'samba-shared'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures samba-shared'
long_description 'Installs/Configures samba-shared'
version '0.1.0'
