name 'useful_packages'
maintainer 'mahdinux'
maintainer_email 'mhashemi@live.ca'
license 'all_rights'
description 'Installs/Configures useful_packages'
long_description 'Installs/Configures useful_packages'
version '0.1.0'
